@hostname = localhost
@port = 4200
@host = {{hostname}}:{{port}}
@entity = department
@contentType = application/json

###
GET http://{{host}}/{{entity}} HTTP/1.1

###
GET http://{{host}}/{{entity}}/112 HTTP/1.1

###
POST http://{{host}}/{{entity}} HTTP/1.1
content-type: {{contentType}}

{
    "description": "samplea"
}

###
PUT http://{{host}}/{{entity}}/4 HTTP/1.1
content-type: {{contentType}}

{
    "description": "plea"
}

###
DELETE  http://{{host}}/{{entity}}/12 HTTP/1.1