@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@entity = login
@contentType = application/json

###
POST http://{{host}}/{{entity}}/get_token HTTP/1.1
content-type:  {{contentType}}

{
    "id": 1
}

###
GET http://{{host}}/{{entity}}/validate_token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoxLCJpZGVudGlmaWNhdGlvbiI6IjEwMDg0MjU5OCIsIm5hbWUiOiJDQVJNRU4gICAgICAgICAgICAgICAgICAgICAgICAiLCJzdXJOYW1lIjoiQ09SUkFMRVMgICAgICAgICAgICAgICAgICAiLCJsYXN0TmFtZSI6Ik1PUkFMRVMgICAgICAgICAgICAgICAgICAgIiwiYmlydGhkYXRlIjoiMTk5OS0wOS0xOFQwMDowMDowMC4wMDBaIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInBob25lIjoiMTIzMzIxMTIzIiwiaWRfc2V4IjoyLCJkZXBhcnRtZW50IjoiVW5pZGFkIGRlIEZpbmFuemFzIn0sImlhdCI6MTY1NDMwNDc0MiwiZXhwIjoxNjU0MzQwNzQyfQ.bzOFhpRNWxXABCqIw-ZFyh_DJzjHP6HQV2WC1-9Y4I0
