@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@entity = login
@contentType = application/json

###
POST http://{{host}}/{{entity}}/get_token HTTP/1.1
content-type:  {{contentType}}

{
    "id": 1
}

###
GET http://{{host}}/{{entity}}/validate_token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InN0YXR1cyI6MjAwLCJpdGVtIjp7ImlkIjoxLCJpZGVudGlmaWNhdGlvbiI6IjEwMDg0MjU5OCIsIm5hbWUiOiJDQVJNRU4gICAgICAgICAgICAgICAgICAgICAgICAiLCJzdXJOYW1lIjoiQ09SUkFMRVMgICAgICAgICAgICAgICAgICAiLCJsYXN0TmFtZSI6Ik1PUkFMRVMgICAgICAgICAgICAgICAgICAgIiwicGljdHVyZSI6bnVsbCwiYmlydGhkYXRlIjoiMTk5OS0wOS0xOFQwMDowMDowMC4wMDBaIiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInBob25lIjoiMTIzMzIxMTIzIiwiaWRfc2V4IjoyLCJkZXBhcnRtZW50IjoiVW5pZGFkIGRlIEZpbmFuemFzIn19LCJpYXQiOjE2NTM5NDc3MDYsImV4cCI6MTY1Mzk4MzcwNn0.s8zoAA-xnb4LM7M_4mhgxkF13vGS2PN6nrpRp4gE1WE
