@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@entity = requests
@contentType = application/json

###
POST http://{{host}}/{{entity}} HTTP/1.1
content-type:  {{contentType}}

{
    "id": 3
}

###
GET http://{{host}}/{{entity}} HTTP/1.1








